### ISSUE TITLE
Use python 3.7 for requirements

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/cartographer_backend#85]
I didn't catch this in my review of PR #80 @helrond , but I thought we had to use python 3.7, not python 3.6 to generate `requirements.txt`. @p-galligan , didn't python 3.6 cause deployment problems for you, so you [switched to 3.7 in your commit on Sept 9](https://github.com/RockefellerArchiveCenter/cartographer_backend/commits/development/requirements.txt)?

**Comment by helrond** [comment]
This is no longer an issue given that we've switched deployment patterns.
